name: block_access
description: Blockchain-based physical access control system
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.1.0
  qr_code_scanner: ^1.0.1
  web3dart: ^2.6.1
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.15
  connectivity_plus: ^3.0.3
  
  # UI Enhancements
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_staggered_animations: ^1.1.1
  simple_animations: ^5.0.0+3
  
  # Additional Features
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  geolocator: ^9.0.2
  flutter_local_notifications: ^14.1.1
  local_auth: ^2.1.6
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.11
  share_plus: ^7.0.2
  package_info_plus: ^4.0.2
  image_picker: ^0.8.7+5
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter_native_splash:
  color: "#3366FF"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/contracts/
    - assets/animations/
    - assets/icons/
    - .env
